#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-init
Version  : 0.2.6
Release  : 9
URL      : https://github.com/clearlinux/clr-init/archive/V0.2.6.tar.gz
Source0  : https://github.com/clearlinux/clr-init/archive/V0.2.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : LVM2
BuildRequires : glibc-bin
BuildRequires : systemd
BuildRequires : systemd-cryptsetup
BuildRequires : systemd-hwdb
BuildRequires : util-linux-bin

%description
## clr-init
Initrd created using systemd as init program
## Luks Encryption support

%prep
%setup -q -n clr-init-0.2.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525391895
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1525391895
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/initrd.d/clr-init.cpio.gz
