#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v2
# autospec commit: 250a6667ebd1
#
Name     : clr-init
Version  : 1.1.0
Release  : 38
URL      : https://github.com/clearlinux/clr-init/archive/V1.1.0/clr-init-1.1.0.tar.gz
Source0  : https://github.com/clearlinux/clr-init/archive/V1.1.0/clr-init-1.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: clr-init-license = %{version}-%{release}
BuildRequires : LVM2
BuildRequires : LVM2-extras
BuildRequires : ModemManager
BuildRequires : NetworkManager
BuildRequires : alsa-utils
BuildRequires : bluez
BuildRequires : btrfs-progs
BuildRequires : clr-systemd-config
BuildRequires : colord
BuildRequires : dosfstools
BuildRequires : e2fsprogs
BuildRequires : fuse
BuildRequires : fwupd
BuildRequires : glibc-bin
BuildRequires : glibc-lib-avx2
BuildRequires : gnome-settings-daemon
BuildRequires : kbd
BuildRequires : keyutils
BuildRequires : kmod
BuildRequires : less
BuildRequires : libinput
BuildRequires : libmtp
BuildRequires : mdadm
BuildRequires : multipath-tools
BuildRequires : pulseaudio
BuildRequires : rdma-core
BuildRequires : systemd
BuildRequires : systemd-extras
BuildRequires : thin-provisioning-tools
BuildRequires : thunderbolt-software-user-space
BuildRequires : udisks2
BuildRequires : upower
BuildRequires : util-linux-bin
BuildRequires : xfsprogs
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## clr-init
Initrd created using systemd as init program
## Luks Encryption support

%package license
Summary: license components for the clr-init package.
Group: Default

%description license
license components for the clr-init package.


%prep
%setup -q -n clr-init-1.1.0
cd %{_builddir}/clr-init-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698703118
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1698703118
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-init
cp %{_builddir}/clr-init-%{version}/COPYING %{buildroot}/usr/share/package-licenses/clr-init/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/initrd.d/clr-init.cpio.gz

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-init/8624bcdae55baeef00cd11d5dfcfa60f68710a02
